### ISSUE TITLE
(Search API) Distinct items by name.

### ISSUE THREAD

**Issue by s3rius** [s3rius/feedEm#38]
Search API is cool, but i got suggestions like this:

![image](https://user-images.githubusercontent.com/18153319/49462219-f34de880-f80e-11e8-970a-c48562e55473.png)

That doesn't seem right.
So we have at least 2 possible ways to solve that:
* Distinct by name on client side.
* Distinct on server side.

**Comment by Kolaer** [comment]
Added seller info into the merch data. It may be more useful.
